version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1

  # different jobs are calles later in the workflows sections
jobs:
  frondend:
    working_directory: ~/app/udagram/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install:
          node-version: "14.18"
      - run:
          name: Install Package Frontend
          command: npm install -f
      - run:
          name: Build Frontend
          command: npm run build
      - aws-cli/install
      - run:
          name: Deploy Frontend
          command: |
            chmod +x ./bin/deploy.sh
            ./bin/deploy.sh
  api:
    working_directory: ~/app/udagram/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install:
          node-version: "14.18"
      - run:
          name: Install Package Frontend
          command: npm install -f
      - run:
          name: Build API
          command: npm run build
      - aws-cli/install
      - eb/install
      - run:
          name: Deploy Api
          command: npm run deploy

workflows:
  udagram:
    jobs:
      - api
