version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@4.0.0

jobs:
  frondend:
    working_directory: ~/app/udagram/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install:
          node-version: "14.18"
      - run:
          name: Install Package
          command: npm install -f
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Build
          command: npm run build
      - aws-cli/install
      - run:
          name: Deploy
          command: |
            chmod +x ./bin/deploy.sh
            ./bin/deploy.sh
  api:
    working_directory: ~/app/udagram/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install:
          node-version: "14.18"
      - run:
          name: Install Package
          command: npm install -f
      - run:
          name: Build
          command: npm run build
      - eb/setup
      - run:
          name: Deploy
          command: |
            chmod +x ./ci/deploy.sh
            ./ci/deploy.sh
            npm run deploy

workflows:
  udagram:
    jobs:
      - frondend
          filters:
            branches:
              only:
                - master
      - api
          filters:
            branches:
              only:
                - master
